services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: archeo_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: archeodb
    ports:
      - "5400:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://archeo_user:secretpassword@db:5432/archeodb

